version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: address-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: address_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: address-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/address_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345
      API_YANDEX_KEY: 86f92be1-69ec-47f1-a8ba-c2a520b3cd82
      API_DADATA_TOKEN: 1c27487ca2ab62b56857c24772ff7b2383d1f73c
      API_DADATA_SECRET: a6f93eca925f61d87a99ccc2f2c5284c65511b15

volumes:
  mysql_data: